### ISSUE TITLE
Unexpected prefixes modification while loading

### ISSUE THREAD

**Issue by sszuev** [avicomp/ont-api#47]
OntologyLoader factrory tries to modify prefixes of already existing ontology.
The following testcase leads to an error:

        public static void main(String ... args) throws Exception {
            // data:
            OntGraphModel b = OntModelFactory.createModel().setID("http://b").getModel();
            OntGraphModel a = OntModelFactory.createModel().setID("http://a").getModel().addImport(b);
            OntologyManager m = OntManagers.createONT();
            // pass 'b':
            UnmodifiableGraph g = new UnmodifiableGraph(b.getGraph());            
            m.addOntology(g);
            // load 'a' :
            String txt = ReadWriteUtils.toString(a, OntFormat.TURTLE);
            OWLOntologyDocumentSource src = new StringInputStreamDocumentSource(txt, OntFormat.TURTLE);
            m.loadOntologyFromOntologyDocument(src);
        }

Stacktrace:

```
Exception in thread "main" org.apache.jena.shared.PrefixMapping$JenaLockedException: pm:{}
	at org.apache.jena.shared.impl.PrefixMappingImpl.checkUnlocked(PrefixMappingImpl.java:115)
	at org.apache.jena.shared.impl.PrefixMappingImpl.setNsPrefix(PrefixMappingImpl.java:79)
	at ru.avicomp.ontapi.jena.utils.Models.lambda$setNsPrefixes$4(Models.java:154)
	at java.util.TreeMap.forEach(TreeMap.java:1005)
	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505)
	at ru.avicomp.ontapi.jena.utils.Models.setNsPrefixes(Models.java:154)
	at ru.avicomp.ontapi.OntologyLoaderImpl.toGraphInfo(OntologyLoaderImpl.java:390)
	at ru.avicomp.ontapi.OntologyLoaderImpl.fetchGraph(OntologyLoaderImpl.java:308)
	at ru.avicomp.ontapi.OntologyLoaderImpl.makeUnionGraph(OntologyLoaderImpl.java:257)
	at ru.avicomp.ontapi.OntologyLoaderImpl.makeUnionGraph(OntologyLoaderImpl.java:182)
	at ru.avicomp.ontapi.OntologyLoaderImpl.createModel(OntologyLoaderImpl.java:136)
	at ru.avicomp.ontapi.OntologyLoaderImpl.load(OntologyLoaderImpl.java:94)
	at ru.avicomp.ontapi.OntologyFactoryImpl.loadOntology(OntologyFactoryImpl.java:76)
	at ru.avicomp.ontapi.OntologyFactory.loadOWLOntology(OntologyFactory.java:133)
	at ru.avicomp.ontapi.OntologyFactory.loadOWLOntology(OntologyFactory.java:36)
	at ru.avicomp.ontapi.OntologyManagerImpl.load(OntologyManagerImpl.java:1513)
	at ru.avicomp.ontapi.OntologyManagerImpl.load(OntologyManagerImpl.java:1482)
	at ru.avicomp.ontapi.OntologyManagerImpl.loadOntologyFromOntologyDocument(OntologyManagerImpl.java:1423)
	at ru.avicomp.ontapi.OntologyManager.loadOntologyFromOntologyDocument(OntologyManager.java:615)
```

**Comment by sszuev** [comment]
bug is fixed.
but an additional work on prefix functionality is needed
