### ISSUE TITLE
Exception while load ontology-hierarchy in jena-unsuported format

### ISSUE THREAD

**Issue by sszuev** [avicomp/ont-api#5]
Spin in Manchester 

Test: https://github.com/avicomp/ont-api/blob/master/src/test/java/ru/avicomp/ontapi/tests/LoadFactoryManagerTest.java (testLoadNotJenaHierarchy())

stacktrace:
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://spinrdf.org/spin> Cause: Ontology already exists. OntologyID(OntologyIRI(<http://spinrdf.org/sp>) VersionIRI(<null>))

	at ru.avicomp.ontapi.OntologyManagerImpl.makeLoadImportRequest(OntologyManagerImpl.java:1725)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.handleOntology(ManchesterOWLSyntaxParserImpl.java:2189)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseOntology(ManchesterOWLSyntaxParserImpl.java:2118)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxOntologyParser.parse(ManchesterOWLSyntaxOntologyParser.java:93)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:192)
	at ru.avicomp.ontapi.OntFactoryImpl$OWLLoaderImpl.load(OntFactoryImpl.java:209)
	at ru.avicomp.ontapi.OntFactoryImpl$OntModelLoaderImpl.loadGraph(OntFactoryImpl.java:578)
	at ru.avicomp.ontapi.OntFactoryImpl$OntModelLoaderImpl.load(OntFactoryImpl.java:259)
	at ru.avicomp.ontapi.OntFactoryImpl.loadOWLOntology(OntFactoryImpl.java:99)
	at ru.avicomp.ontapi.OntFactoryImpl.loadOWLOntology(OntFactoryImpl.java:59)
	at ru.avicomp.ontapi.OntologyManagerImpl.load(OntologyManagerImpl.java:1636)
	at ru.avicomp.ontapi.OntologyManagerImpl.load(OntologyManagerImpl.java:1602)
	at ru.avicomp.ontapi.OntologyManagerImpl.load(OntologyManagerImpl.java:1584)
	at ru.avicomp.ontapi.OntologyManagerImpl.loadImports(OntologyManagerImpl.java:1693)
	at ru.avicomp.ontapi.OntologyManagerImpl.makeLoadImportRequest(OntologyManagerImpl.java:1720)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.handleOntology(ManchesterOWLSyntaxParserImpl.java:2189)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseOntology(ManchesterOWLSyntaxParserImpl.java:2118)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxOntologyParser.parse(ManchesterOWLSyntaxOntologyParser.java:93)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:192)
	at ru.avicomp.ontapi.OntFactoryImpl$OWLLoaderImpl.load(OntFactoryImpl.java:209)
	at ru.avicomp.ontapi.OntFactoryImpl$OntModelLoaderImpl.loadGraph(OntFactoryImpl.java:578)
	at ru.avicomp.ontapi.OntFactoryImpl$OntModelLoaderImpl.load(OntFactoryImpl.java:259)
	at ru.avicomp.ontapi.OntFactoryImpl.loadOWLOntology(OntFactoryImpl.java:99)
	at ru.avicomp.ontapi.OntFactoryImpl.loadOWLOntology(OntFactoryImpl.java:59)
	at ru.avicomp.ontapi.OntologyManagerImpl.load(OntologyManagerImpl.java:1636)
	at ru.avicomp.ontapi.OntologyManagerImpl.load(OntologyManagerImpl.java:1602)
	at ru.avicomp.ontapi.OntologyManagerImpl.loadOntologyFromOntologyDocument(OntologyManagerImpl.java:1545)
	at ru.avicomp.ontapi.OntologyManager.loadOntologyFromOntologyDocument(OntologyManager.java:235)
	at ru.avicomp.ontapi.tests.LoadFactoryManagerTest.testLoadNotJenaHierarchy(LoadFactoryManagerTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.semanticweb.owlapi.model.OWLOntologyAlreadyExistsException: Ontology already exists. OntologyID(OntologyIRI(<http://spinrdf.org/sp>) VersionIRI(<null>))
	at ru.avicomp.ontapi.OntFactoryImpl$OntModelLoaderImpl.createModel(OntFactoryImpl.java:315)
	at ru.avicomp.ontapi.OntFactoryImpl$OntModelLoaderImpl.load(OntFactoryImpl.java:270)
	at ru.avicomp.ontapi.OntFactoryImpl.loadOWLOntology(OntFactoryImpl.java:99)
	at ru.avicomp.ontapi.OntFactoryImpl.loadOWLOntology(OntFactoryImpl.java:59)
	at ru.avicomp.ontapi.OntologyManagerImpl.load(OntologyManagerImpl.java:1636)
	at ru.avicomp.ontapi.OntologyManagerImpl.load(OntologyManagerImpl.java:1602)
	at ru.avicomp.ontapi.OntologyManagerImpl.load(OntologyManagerImpl.java:1584)
	at ru.avicomp.ontapi.OntologyManagerImpl.loadImports(OntologyManagerImpl.java:1693)
	at ru.avicomp.ontapi.OntologyManagerImpl.makeLoadImportRequest(OntologyManagerImpl.java:1720)
	... 50 more

**Comment by sszuev** [comment]
fix https://github.com/avicomp/ont-api/commit/da8c408f89400fcc7ea091928a60c4dd9fa30f25
